name: MACH_VII_v2.0
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bullet-cpp=3.25=hed136d8_5
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2026.1.4=h4c7d964_0
  - icu=78.2=h637d24d_0
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libsqlite=3.51.2=hf5d6505_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - mkl=2025.3.0=hac47afa_455
  - numpy=1.26.4=py310hf667824_0
  - openssl=3.6.1=hf411b9b_1
  - pip=25.3=pyh8b19718_0
  - pybullet=3.25=py310h9d10cbf_5
  - python=3.10.19=hc20f281_3_cpython
  - python_abi=3.10=8_cp310
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.10.1=pyh332efcf_0
  - tbb=2022.3.0=h3155e25_2
  - tk=8.6.13=h6ed50ae_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - wheel=0.46.3=pyhd8ed1ab_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - async-timeout==4.0.3
      - attrs==25.4.0
      - bidict==0.23.1
      - blinker==1.9.0
      - cachetools==6.2.6
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - exceptiongroup==1.3.1
      - falkordb==1.4.0
      - fastapi==0.99.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.3.1
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==1.3.4
      - idna==3.11
      - jinja2==3.1.6
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langchain==0.2.16
      - langchain-classic==1.0.1
      - langchain-community==0.2.16
      - langchain-core==0.2.38
      - langchain-text-splitters==0.2.4
      - langgraph==1.0.7
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.3
      - langsmith==0.1.147
      - markupsafe==3.0.3
      - marshmallow==3.26.2
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - networkx==3.4.2
      - opencv-python==4.11.0.86
      - orjson==3.11.5
      - ormsgpack==1.12.2
      - packaging==24.2
      - pandas==2.3.3
      - pillow==12.1.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pyarrow==23.0.0
      - pydantic==1.10.26
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pydeck==0.9.1
      - pyparsing==3.3.2
      - pyrealsense2==2.56.5.9235
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-engineio==4.13.0
      - python-socketio==5.16.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - redis==7.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - sqlalchemy==2.0.46
      - starlette==0.27.0
      - streamlit==1.53.1
      - sympy==1.14.0
      - tenacity==8.5.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - transformers==5.0.0
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ultralytics==8.4.8
      - ultralytics-thop==2.0.18
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - uvicorn==0.40.0
      - watchdog==6.0.0
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==16.0
      - wsproto==1.3.2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: C:\Users\AI-510-152\anaconda3\envs\MACH_VII_v2.0
