name: MACH_VII_v2.0
channels:
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
    - fastapi==0.99.1
    - uvicorn==0.40.0
    - websockets==16.0
    - requests==2.32.5
    - numpy==2.4.1
    - opencv-python==4.13.0.90
    - ultralytics==8.4.8
    - langchain==0.2.16
    - langchain-community==0.2.16
    - langchain-core==0.2.38
    - langchain-text-splitters==0.2.4
    - langsmith==0.1.147
    - pydantic==1.10.26
    - torch==2.9.1
    - torchvision==0.24.1
    - falkordb==1.4.0
    - python-dotenv==1.2.1