name: pybullet_env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.12.9=h14ffc60_0
  - conda-forge::pybullet
  - setuptools=80.9.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - bidict==0.23.1
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - dnspython==2.8.0
      - flask==3.1.0
      - flask-socketio==5.6.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - greenlet==3.3.0
      - h11==0.16.0
      - idna==3.11
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.14.0
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - python-engineio==4.13.0
      - python-socketio==5.16.0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - simple-websocket==1.1.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.2
      - streamlit-autorefresh==1.0.1
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.4
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - watchdog==6.0.0
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - wsproto==1.3.2
prefix: C:\Users\AI-510-170\anaconda3\envs\pybullet_env
